In [12]:
import pandas as pd
import scrapy

In [2]:
!scrapy startproject news_scraper

New Scrapy project 'news_scraper', using template directory 'C:\Users\rebec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scrapy\templates\project', created in:
    C:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

You can start your first spider with:
    cd news_scraper
    scrapy genspider example example.com

In [3]:
%cd news_scraper

c:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

In [9]:
%%writefile "sitemap_spider.py"
import scrapy
class SitemapSpider(scrapy.Spider):
    name = 'sitemap_spider'
    start_urls = ['https://www.elcomercio.es/sitemap.xml',
                  'https://www.lne.es/sitemap_google_news_52e19.xml',
                  'https://www.larazon.es/sitemaps/news.xml',
                  'https://www.lavanguardia.com/sitemap-google-news.xml',
                  'https://www.rtpa.es/sitemap-noticias.xml',
                  'https://www.europapress.es/news_sitemap_1.xml',
                  'https://www.abc.es/sitemap.xml',
                  'https://www.20minutos.es/sitemap-google-news.xml',
                  'https://www.elperiodico.com/es/google-news.xml',
                  'https://www.eldiario.es/sitemap_google_news_25b87.xml']
    #custom_settings = {
    #    'ROBOTSTXT_OBEY': False
    #}

    namespaces = {
        'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',  # Default namespace
        'news': 'http://www.google.com/schemas/sitemap-news/0.9'
    }

    def parse(self, response):
        # Extraer datos de cada tag <url>
        for url in response.xpath('//ns:url', namespaces=self.namespaces):
            loc = url.xpath('./ns:loc/text()', namespaces=self.namespaces).get()
            title = url.xpath('./news:news/news:title/text()', namespaces=self.namespaces).get()
            publication_date = url.xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            publisher = url.xpath('./news:news/news:publication/news:name/text()', namespaces=self.namespaces).get()

            yield {
                'fuente': publisher,
                'url': loc,
                'titulo': title,
                'fecha_publicacion': publication_date,
            }

Overwriting sitemap_spider.py

In [10]:
copy sitemap_spider.py news_scraper\spiders

        1 archivo(s) copiado(s).

In [11]:
!scrapy crawl sitemap_spider -o news_output.csv

2025-02-15 12:42:50 [scrapy.utils.log] INFO: Scrapy 2.12.0 started (bot: news_scraper)
2025-02-15 12:42:50 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.10.0, w3lib 2.3.1, Twisted 24.3.0, Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)], pyOpenSSL 25.0.0 (OpenSSL 3.3.2 3 Sep 2024), cryptography 43.0.3, Platform Windows-10-10.0.19045-SP0
2025-02-15 12:42:50 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-15 12:42:50 [asyncio] DEBUG: Using selector: SelectSelector
2025-02-15 12:42:50 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2025-02-15 12:42:50 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2025-02-15 12:42:50 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2025-02-15 12:42:50 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2025-02-15 12:42:50 [scrapy.extensions.telnet] INFO: Telnet Password: bd2a19a2d4ba3309
2025-02-15 12:42:51 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-15 12:42:51 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'news_scraper',
 'FEED_EXPORT_ENCODING': 'utf-8',
 'NEWSPIDER_MODULE': 'news_scraper.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['news_scraper.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2025-02-15 12:42:56 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-15 12:42:56 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-15 12:42:56 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-15 12:42:56 [scrapy.core.engine] INFO: Spider opened
2025-02-15 12:42:56 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-15 12:42:56 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.lavanguardia.com/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.larazon.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.elcomercio.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.rtpa.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.lne.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.abc.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.20minutos.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.rtpa.es/sitemap-noticias.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.europapress.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.elcomercio.es/sitemap.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.larazon.es/sitemaps/news.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.lavanguardia.com/sitemap-google-news.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sucesos/2025-02-15/La-busqueda-del-desaparecido-en-Llanes-se-centra-entre-las-playas-de-La-Huelga-y-Toro_111739618463.html', 'titulo': 'La búsqueda del desaparecido en Llanes se centra entre las playas de La Huelga y Toró', 'fecha_publicacion': '2025-02-15'}
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.lne.es/sitemap_google_news_52e19.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.eldiario.es/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.elperiodico.com/robots.txt> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.abc.es/sitemap.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sociedad/2025-02-15/El-Principado-destaca-el-potencial-del-turismo-astronomico-en-el-medio-rural_111739616432.html', 'titulo': 'El Principado destaca el potencial del turismo astronómico en el medio rural', 'fecha_publicacion': '2025-02-15'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-15/Asturias-cierra-2024-con-un-aumento-de-los-accidentes-laborales-graves-y-mortales_111739611229.html', 'titulo': 'Asturias cierra 2024 con un aumento de los accidentes laborales graves y mortales', 'fecha_publicacion': '2025-02-15'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-nacional/2025-02-14/Las-comunidades-del-PP-frenan-el-plan-de-salud-mental-ante-las-criticas-de-los-psiquiatras_111739541356.html', 'titulo': 'Sanidad y las comunidades aprueban el primer plan antisuicidio con medidas de prevención', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sociedad/2025-02-14/La-cineasta-Iciar-Bollain-considera-que-la-ultraderecha-busca-tergiversar-el-feminismo_111739563099.html', 'titulo': 'La cineasta Icíar Bollaín considera que la ultraderecha busca tergiversar el feminismo', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Anembe-apoya-las-medidas-del-Principado-para-controlar-los-focos-de-tuberculosis_111739561596.html', 'titulo': 'Anembe apoya las medidas del Principado para controlar los focos de tuberculosis', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sucesos/2025-02-14/Los-equipos-reanudan-la-busqueda-del-cantabro-desaparecido-el-martes-en-la-zona-de-Gulpiyuri_111739521703.html', 'titulo': 'Finaliza sin éxito y por cuarto día la búsqueda del vecino de Cantabria desaparecido en la costa oriental', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sociedad/2025-02-14/Piden-una-unidad-multidisciplinar-en-Asturias-para-menores-con-cardiopatias-congenitas_111739559658.html', 'titulo': 'Piden una unidad multidisciplinar en Asturias para menores con cardiopatías congénitas', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-economia/2025-02-14/El-consorcio-vasco-liderado-por-Sidenor-compra-el-30-de-Talgo-por-155-millones-de-euros_111739557255.html', 'titulo': 'El consorcio vasco liderado por Sidenor compra el 30% de Talgo por 155 millones de euros', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Asturias-contara-con-la-primera-ley-de-ciencia-autonomica-del-pais_111739538751.html', 'titulo': 'Asturias contará con la primera ley de ciencia autonómica del país', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/El-acusado-de-asesinar-a-Tatiana-Coinac-acepta-una-pena-de-42-años-de-carcel_111739534935.html', 'titulo': 'El acusado de asesinar a Tatiana Coinac acepta una pena de 42 años de cárcel', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.20minutos.es/sitemap-google-news.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.europapress.es/news_sitemap_1.xml> (referer: None)
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-nacional/2025-02-14/Visto-para-sentencia-el-juicio-a-Rubiales-tras-renunciar-los-acusados-a-la-ultima-palabra_111739534532.html', 'titulo': 'Visto para sentencia el juicio a Rubiales tras renunciar los acusados a la última palabra', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/El-pleno-de-Gijon-aprueba-la-modificacion-del-PGO-para-el-hospital-de-Quiron_111739523068.html', 'titulo': 'El pleno de Gijón aprueba la modificación del PGO para el hospital de Quirón', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Un-grupo-de-repartidores-demanda-a-Glovo-por-contratar-a-trabajadores-de-otras-empresas_111739529958.html', 'titulo': 'Un grupo de repartidores demanda a Glovo por contratar a trabajadores de otras empresas', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-economia/2025-02-14/El-IPC-acentua-su-subida-en-Asturias-al-3,2-anual-en-enero,-con-los-alimentos-al-2,2_111739522345.html', 'titulo': 'El IPC acentúa su subida en Asturias al 3,2% anual en enero, con los alimentos al 2,2%', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-sucesos/2025-02-14/Herido-leve-un-repartidor-al-perder-el-control-de-su-moto-en-Gijon_111739560293.html', 'titulo': 'Herido leve un repartidor al perder el control de su moto en Gijón', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Ocho-de-cada-diez-niños-diagnosticados-de-cancer-en-el-HUCA-sobreviven-a-la-enfermedad_111739537244.html', 'titulo': 'Ocho de cada diez niños diagnosticados de cáncer en el HUCA sobreviven a la enfermedad', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Los-trabajadores-de-la-Papelera-de-Navia-se-concentran-para-reclamar-un-cambio-en-el-modelo-de-produccion-de-la-empresa_111739537446.html', 'titulo': 'La plantilla de ENCE se moviliza ante la bajada de la producción en la papelera de Navia  ', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Los-vecinos-quieren-convertir-la-mina-de-Llumeres-en-un-parque-de-patrimonio-industrial_111739537031.html', 'titulo': 'Los vecinos quieren convertir la mina de Llumeres en un parque de patrimonio industrial', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/El-Banco-de-Tierras-del-Principado-dara-ayudas-para-el-traspaso-de-explotaciones-agrarias_111739537082.html', 'titulo': 'El Banco de Tierras del Principado dará ayudas para el traspaso de explotaciones agrarias', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Enfoca-Talento-logro-emplear-a-un-60-de-las-participantes-en-anteriores-ediciones_111739537618.html', 'titulo': "'Enfoca Talento' logró emplear a un 60% de las participantes en anteriores ediciones", 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:57 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-internacional/2025-02-14/Donald-Trump-anuncia-&quot;aranceles-reciprocos&quot;,-con-la-Union-Europea-como-una-de-las-mayores-damnificadas_111739521189.html', 'titulo': 'La UE dice que su reacción a los aranceles de EEUU será "firme e inmediata"', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/CCOO-defiende-al-jefe-de-explotacion-de-Valgrande-Pajares-y-responsabiliza-al-director_111739524271.html', 'titulo': 'El Partido Popular exige una respuesta rápida y efectiva en Valgrande-Pajares', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/El-PP-acusa-a-Roqueñi-de-mentir-al-desvincular-en-la-Junta-el-brote-de-Pravia-con-el-estado-del-agua_111739541233.html', 'titulo': 'El PP acusa a Roqueñí de mentir al desvincular en la Junta el brote de Pravia con el estado del agua', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-internacional/2025-02-14/Trump-dice-que-habra-una-reunion-de-alto-nivel-en-Munich-entre-EEUU,-Rusia-y-Ucrania_111739520548.html', 'titulo': 'Zelenski niega tener conocimiento de ninguna reunión prevista con Rusia en Múnich', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-internacional/2025-02-14/El-papa-anula-su-agenda-hasta-el-lunes-tras-ser-hospitalizado-por-una-bronquitis_111739540091.html', 'titulo': 'El papa anula su agenda hasta el lunes tras ser hospitalizado por una bronquitis', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.elcomercio.es/sitemap.xml>

{'fuente': 'El Comercio: Diario de Asturias', 'url': 'https://www.elcomercio.es/sociedad/papa-francisco-pasa-tranquilo-primera-noche-hospitalizacion-20250215123310-ntrc.html', 'titulo': 'El papa Francisco pasa «tranquilo» su primera noche de hospitalización por bronquitis', 'fecha_publicacion': '2025-02-15T12:33:11+01:00'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.larazon.es/sitemaps/news.xml>

{'fuente': 'La Razón', 'url': 'https://www.larazon.es/ciencia/este-animal-alimenta-sus-crias-sus-propias-heces-salvarle-vida_2025021567b07d7e500f9600010e3999.html', 'titulo': 'Este animal alimenta a sus crías con sus propias heces para salvarle la vida', 'fecha_publicacion': '2025-02-15T12:41:50+01:00'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.lavanguardia.com/sitemap-google-news.xml>

{'fuente': 'La Vanguardia', 'url': 'https://www.lavanguardia.com/loterias/20250215/10388912/loteria-nacional-sorteo-extraordinario-san-valentin-hoy-sabado-15-de-febrero-resultado-premios-en-directo.html', 'titulo': 'Lotería Nacional, en directo: Resultados del sorteo extraordinario de San Valentín, premios y números ganadores de hoy', 'fecha_publicacion': '2025-02-15T12:12:07+01:00'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/Dieciseis-familias-de-Contrueces-piden-al-Ayuntamiento-ayuda-para-no-ser-desalojados-por-Sareb,-el-&quot;banco-malo&quot;_111739539962.html', 'titulo': 'Dieciséis familias de Contrueces piden al Ayuntamiento ayuda para no ser desalojados por Sareb, el "banco malo"', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>

{'fuente': 'Radiotelevisión del Principado de Asturias', 'url': 'https://www.rtpa.es/noticias-asturias/2025-02-14/La-Fiscalia-pide-prision-para-el-hombre-atrincherado-en-una-vivienda-de-Mieres_111739539140.html', 'titulo': 'La Fiscalía pide prisión para el hombre atrincherado en una vivienda de Mieres', 'fecha_publicacion': '2025-02-14'}
2025-02-15 12:42:58 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.rtpa.es/sitemap-noticias.xml>


In [17]:
data_df = pd.read_csv("news_output.csv")
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], errors='coerce', utc=True)
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'].dt.strftime("%Y-%m-%d"))
# fecha_inicial = pd.Timestamp("2025-2-1")
# data_df = data_df[data_df['fecha_publicacion'] >= fecha_inicial].drop_duplicates().reset_index(drop='True')
data_df

,fuente,url,titulo,fecha_publicacion
0,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sucesos/2025-02-1...,La búsqueda del desaparecido en Llanes se cent...,2025-02-15
1,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,El Principado destaca el potencial del turismo...,2025-02-15
2,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-asturias/2025-02-...,Asturias cierra 2024 con un aumento de los acc...,2025-02-15
3,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-nacional/2025-02-...,Sanidad y las comunidades aprueban el primer p...,2025-02-14
4,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,La cineasta Icíar Bollaín considera que la ult...,2025-02-14
...,...,...,...,...
6201,Europa Press,https://www.europapress.es/murcia/noticia-ayun...,El Ayuntamiento de Murcia destina más de 145.0...,NaT
6202,Europa Press,https://www.europapress.es/islas-canarias/noti...,El Gobierno de Canarias declara la prealerta p...,NaT
6203,Europa Press,https://www.europapress.es/navarra/noticia-tcc...,"TCC muestra su ""voluntad de continuar con las ...",NaT
6204,Europa Press,https://www.europapress.es/castilla-lamancha/n...,"Consejo de Gobierno aprueba el martes 3,3 mill...",NaT
6205,Europa Press,https://www.europapress.es/comunitat-valencian...,Costas inicia las obras del nuevo espigón de l...,NaT

In [18]:
# Articulos por fuente
data_df['fuente'].value_counts()

fuente
Europa Press                                  1000
La Razón                                       973
La Vanguardia                                  940
ABC.es                                         833
20minutos                                      606
La Nueva España                                500
ElDiario.es                                    473
<![CDATA[El Periódico]]>                       450
El Comercio: Diario de Asturias                310
Radiotelevisión del Principado de Asturias      94
Vertele                                         27
Name: count, dtype: int64

# Accedemos al contenido de las noticias

In [19]:
!pip install -q newspaper4k
!pip install -q lxml_html_clean

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\rebec\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\rebec\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [21]:
from newspaper import Article, build, Config

## Usando Newspaper

In [ ]:
config = Config()
config.browser_user_agent = 'Mozilla/5.0 (Linux; Android 10; Pixel 3 XL Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36'
config.request_timeout = 10
config.language= 'es'
config.request_timeout = 5
config.thread_timeout_seconds = 5
config.memoize_articles = False
config.fetch_images = False
config.follow_meta_refresh = True
config.number_threads = 16
config.headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Cache-Control": "max-age=0",
}

def extraer_texto_articulos(url):
    try:
        article = Article(url, config=config)
        article.download()
        article.parse()
        return article.text
    except Exception:
        print(f"Error en url: {url}")
        return None

data_df['texto'] = data_df['url'].apply(extraer_texto_articulos)

#84m 19.6s

Error en url: https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en url: https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en url: https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html

In [24]:
data_df

,fuente,url,titulo,fecha_publicacion,texto
0,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sucesos/2025-02-1...,La búsqueda del desaparecido en Llanes se cent...,2025-02-15,Una treintena de efectivos de la Guardia Civil...
1,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,El Principado destaca el potencial del turismo...,2025-02-15,El MUJA acoge la I Jornadas de Divulgación Cie...
2,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-asturias/2025-02-...,Asturias cierra 2024 con un aumento de los acc...,2025-02-15,El Principado registró el pasado año 11.765 ac...
3,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-nacional/2025-02-...,Sanidad y las comunidades aprueban el primer p...,2025-02-14,Las comunidades del PP frenan el plan de salud...
4,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,La cineasta Icíar Bollaín considera que la ult...,2025-02-14,La directora y guionista recibe el Galardón po...
...,...,...,...,...,...
6201,Europa Press,https://www.europapress.es/murcia/noticia-ayun...,El Ayuntamiento de Murcia destina más de 145.0...,NaT,Se trata de la rehabilitación sostenible de lo...
6202,Europa Press,https://www.europapress.es/islas-canarias/noti...,El Gobierno de Canarias declara la prealerta p...,NaT,LAS PALMAS DE GRAN CANARIA 14 Feb. (EUROPA PRE...
6203,Europa Press,https://www.europapress.es/navarra/noticia-tcc...,"TCC muestra su ""voluntad de continuar con las ...",NaT,PAMPLONA 14 Feb. (EUROPA PRESS) -\n\nMoventis ...
6204,Europa Press,https://www.europapress.es/castilla-lamancha/n...,"Consejo de Gobierno aprueba el martes 3,3 mill...",NaT,TOLEDO 14 Feb. (EUROPA PRESS) -\n\nEl Consejo ...
6205,Europa Press,https://www.europapress.es/comunitat-valencian...,Costas inicia las obras del nuevo espigón de l...,NaT,"ALICANTE, 14 Feb. (EUROPA PRESS) -\n\nLa Direc..."

Extraer el contenido en paralelo

In [ ]:
from concurrent.futures import ThreadPoolExecutor
import time
data_df = data_df.iloc[:, :-1]

num_threads = 16
start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulos, data_df['url']))
print(f"--- {(time.time() - start_time):.2f}s seconds ---")
#37m 51.4s

Error en url: https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en url: https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en url: https://www.eldiario.es/comunitat-valenciana/comarcas/adif-adjudica-2-1-millones-obras-supresion-paso-nivel-tavernes_1_12054093.html
Error en url: https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en url: https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html
--- 2271.51s seconds ---

In [ ]:
from concurrent.futures import ThreadPoolExecutor
data_df = data_df.iloc[:, :-1]
num_threads = 8
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulos, data_df['url']))
#39m 2.2s

Error en url: https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en url: https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en url: https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en url: https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html

In [28]:
mascara_faltantes = data_df['texto'].isnull()
datos_faltantes = data_df[mascara_faltantes]
print(f'Articulos que no pudo obtener la librería: {len(datos_faltantes)}')

Articulos que no pudo obtener la librería: 4

Segunda pasada para obtener el contenido debido a que la primera extracción a veces falla

In [29]:
data_df.loc[mascara_faltantes, 'texto'] = data_df[mascara_faltantes]['url'].apply(extraer_texto_articulos).copy()

Error en url: https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en url: https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en url: https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en url: https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html

In [30]:
mascara_faltantes = data_df['texto'].isnull()
datos_faltantes = data_df[mascara_faltantes]
print(f'Articulos que no pudo obtener la librería: {len(datos_faltantes)}')

Articulos que no pudo obtener la librería: 4

In [31]:
data_df.head(10)

,fuente,url,titulo,fecha_publicacion,texto
0,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sucesos/2025-02-1...,La búsqueda del desaparecido en Llanes se cent...,2025-02-15,Una treintena de efectivos de la Guardia Civil...
1,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,El Principado destaca el potencial del turismo...,2025-02-15,El MUJA acoge la I Jornadas de Divulgación Cie...
2,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-asturias/2025-02-...,Asturias cierra 2024 con un aumento de los acc...,2025-02-15,El Principado registró el pasado año 11.765 ac...
3,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-nacional/2025-02-...,Sanidad y las comunidades aprueban el primer p...,2025-02-14,Las comunidades del PP frenan el plan de salud...
4,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,La cineasta Icíar Bollaín considera que la ult...,2025-02-14,La directora y guionista recibe el Galardón po...
5,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-asturias/2025-02-...,Anembe apoya las medidas del Principado para c...,2025-02-14,Aconseja que se frenen los movimientos de las ...
6,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sucesos/2025-02-1...,Finaliza sin éxito y por cuarto día la búsqued...,2025-02-14,Más de 40 efectivos buscan al hombre por tierr...
7,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-sociedad/2025-02-...,Piden una unidad multidisciplinar en Asturias ...,2025-02-14,Una exposición conmemora el Día de Mundial de ...
8,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-economia/2025-02-...,El consorcio vasco liderado por Sidenor compra...,2025-02-14,El episodio de la venta de Talgo comenzó hace ...
9,Radiotelevisión del Principado de Asturias,https://www.rtpa.es/noticias-asturias/2025-02-...,Asturias contará con la primera ley de ciencia...,2025-02-14,Está previsto que se apruebe en el pleno del p...

Reintentos automáticamente

In [33]:
import pandas as pd
from newspaper import Article, Config
import time

# Configuración de newspaper
config = Config()
config.browser_user_agent = 'Mozilla/5.0 (Linux; Android 10; Pixel 3 XL Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36'
config.request_timeout = 10
config.language = 'es'
config.fetch_images = False
config.memoize_articles = False

def extraer_texto_articulo(url, max_reintentos=3, espera=2):
    """Intenta extraer el texto de un artículo con reintentos automáticos."""
    for intento in range(max_reintentos):
        try:
            article = Article(url, config=config)
            article.download()
            article.parse()
            
            # Si se obtiene texto, devolverlo
            if article.text:
                return article.text
        except Exception as e:
            print(f"Error en intento {intento + 1} para {url}: {e}")
        
        # Esperar antes de reintentar
        time.sleep(espera)

    # Si después de los reintentos sigue fallando, devolver None
    return None


# Eliminar la última columna
data_df = data_df.iloc[:, :-1]

# Número de hilos a usar
num_threads = 16

start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulo, data_df['url']))

print(f"--- Extracción completada en {(time.time() - start_time):.2f} segundos ---")

# Guardar los resultados en un nuevo CSV
data_df.to_csv("resultados.csv", index=False)
print("Archivo guardado como 'resultados.csv'.")

Error en intento 1 para https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html: Article `download()` failed with Status code 404 for url None on URL https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en intento 2 para https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html: Article `download()` failed with Status code 404 for url None on URL https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en intento 3 para https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html: Article `download()` failed with Status code 404 for url None on URL https://www.lne.es/internacional/2025/02/15/zelenski-pide-crear-ejercito-europeo-114332922.html
Error en intento 1 para https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt: Article `download()` failed with Status code 404 for url None on URL https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en intento 2 para https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt: Article `download()` failed with Status code 404 for url None on URL https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en intento 3 para https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt: Article `download()` failed with Status code 404 for url None on URL https://www.elcomercio.es/asturias/carnaval/charangas/carnaval-asturias-antroxu-gijon-charanga-kopavino20250215193421-nt
Error en intento 1 para https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en intento 2 para https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en intento 3 para https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/mascarada-ancestral-zamarrones-que-puedes-perder-cantabria_2025021467af2d79500f9600010d50eb.html
Error en intento 1 para https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html
Error en intento 2 para https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html
Error en intento 3 para https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html: Article `download()` failed with Status code 404 for url None on URL https://www.larazon.es/cultura/cine/estas-son-mejores-peliculas-romanticas-ver-san-valentin-segun_2025021467aee2f6417ec20001f95d8e.html
--- Extracción completada en 1727.57 segundos ---
Archivo guardado como 'resultados.csv'.

## Extracción con request y palabras clave

In [ ]:
import requests
from bs4 import BeautifulSoup

headers={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Cache-Control": "max-age=0",
}

def extraer_texto_articulos_request(url):
    try:
        response = requests.get(url, headers=headers )
        html_str = response.content
        soup = BeautifulSoup(html_str, 'lxml')
        # Eliminar footer
        footer = soup.find('footer')
        if footer:
            footer.decompose()

        # Encontrar todos los <a> tags
        #for a_tag in soup.find_all('a'):
        #    # Eliminar todos los parrafos dentro de <a> tag
        #    for p_tag in a_tag.find_all('p'):
        #        p_tag.decompose()
        text_content = soup.find_all('p')

        text = ''
        for i in text_content:
            text += i.text.strip() + " "
        return text
    except Exception:
        print(f"Error en url: {url}")
        return None